#ifndef MTR_CONFIG_FILE
#define MTR_CONFIG_FILE

#define CONFIG_PORT_CONNECTED_PIN_AMOUNT 1

#define CONFIG_EEPROM_BUFFER_BYTE_SIZE 4096

//#define CONFIG_UART_ENABLE_MAGIC_CODE
#define CONFIG_USB_ENABLE_MAGIC_CODE
#define AUTORESET

//CORE
#define CONFIG_CURRENT_CLOCK_HZ 128000000
#define CONFIG_RST_CLK_PLL_MULTIPL RST_CLK_CPU_PLLmul16

//PLANNER
#define CONFIG_PLANNER_TIMER TIMER2
#define CONFIG_PLANNER_TIMER_IRQ Timer2_IRQHandler
#define CONFIG_PLANNER_FORCE_RUN_TASK_COUNTER 100

//TIMER defines
#define CONFIG_CLOCK_TIMER_DIVISOR TIMER_HCLKdiv16
#define CONFIG_CLOCK_TIMER_HZ (CONFIG_CURRENT_CLOCK_HZ / (1 << CONFIG_CLOCK_TIMER_DIVISOR))
#define CONFIG_TIMER_NVIC_PRIORITY 2

#define CONFIG_MODBUS_ENABLE_ETHERNET
#define CONFIG_MODBUS_TCP_PORT 502

//UART
#define	CONFIG_UART_HLCK UART_HCLKdiv16
#define CONFIG_UART_BUFFER_BYTE_SIZE 512
#define CONFIG_UART_NVIC_PRIORITY 1
#define CONFIG_UART_TIMER TIMER3
#define CONFIG_UART_TIMER_IRQ Timer3_IRQHandler
#define	CONFIG_UART_TIMER_DIV 8
#define CONFIG_UART2_ENABLE_LIBRARY_INTERRUPT
#define CONFIG_UART1_ENABLE_LIBRARY_INTERRUPT

//MODBUS
#define CONFIG_MODBUS_RTU_TIMEOUT_MS 50

#define CONFIG_MODBUS_MAX_AMOUNT_INPUT_REGISTERS_PER_SLAVE 20
#define CONFIG_MODBUS_MAX_AMOUNT_HOLDING_REGISTERS_PER_SLAVE 20

#define CONFIG_MODBUS_MAX_PULLING_HOLDING_REGISTER_NUM_PER_CONNECTION 20
#define CONFIG_MODBUS_MAX_PULLING_INPUT_REGISTER_NUM_PER_CONNECTION 20

#define CONFIG_MODBUS_RTU_MASTER_DECREASE_VALUE_FOR_ONLINE 2
#define CONFIG_MODBUS_RTU_MASTER_RECENTY_GOOD_MESSAGES_AS_ONLINE 5

#define CONFIG_MODBUS_CONNECTED_DEVICE_NUM 16
#define CONFIG_UART_PROCESSING_RECIEVED_MESSAGE_IN_BYTES 4

#define CONFIG_CAN_NVIC_PRIORITY 1

#define HOLDING_REGISTERS_AMOUNT 10
#define INPUT_REGISTERS_AMOUNT 10

//BUTTONS
#define CONFIG_BUTTON_MAX_AMOUNT 3
#define CONFIG_BUTTON_TRIGGER_VALUE 5
#define CONFIG_BUTTON_HOLDING_VALUE 20
#define CONFIG_BUTTON_TRIGGER_RELEASE_AFTER_HOLDING

//ETHERNET TIMER defines
//#define CONFIG_ETHERNET_TIMER TIMER1
#define CONFIG_ETHERNET_TIMER_IRQ Timer1_IRQHandler
#define	CONFIG_ETHERNET_TIMER_DIV 8

#define DebugNotCheck

#include "mtr_tcpip/mtr_tcp_defines.h"

#endif
