#ifndef INC_DEVICE_H_
#define INC_DEVICE_H_

#include <stdint.h>

//RS485
#define INTERNAL_RS		Uart1Connection
#define EXTERNAL_RS		Uart2Connection

//LEDs
#define WORK_LED				LED0
#define WARNING_LED				LED1

#define CONTACT_WORK_LED		PORTB, PIN2
#define CONTACT_WARNING_LED		PORTB, PIN1

//Buttons
#define INCREMENT_ADDRESS_SLAVE_FOR_ASSIGNMENT_MODE_MASTER_BUTTON	BTN0
#define ASSIGNMENT_MODE_MASTER_BUTTON								BTN1
#define FEEDBACK_WIRTE_ADDRESS_SLAVE_BUTTON							BTN2

#define CONTACT_INCREMENT_ADDRESS_ASSIGNMENT_MODE_MASTER_BUTTON		PORTB, PIN0
#define CONTACT_ASSIGNMENT_MODE_MASTER_BUTTON						PORTA, PIN15
#define CONTACT_FEEDBACK_WIRTE_ADDRESS_SLAVE_BUTTON					PORTB, PIN3

//Internal RS
#define ENABLE_INTERNAL_RS		PORTC, PIN2, false
#define TX_INTERNAL_RS			PORTC, PIN3, MAIN
#define RX_INTERNAL_RS			PORTC, PIN4, MAIN

//EXTERNAL RS
#define ENABLE_EXTERNAL_RS		PORTA, PIN0, false
#define TX_EXTERNAL_RS			PORTC, PIN13, OVERRID
#define RX_EXTERNAL_RS			PORTC, PIN14, OVERRID

//INTERFACE EXPANSION BOARD
#define POWER_EXTERNAL_RS_ON_INTERFACE_EXPANSION_BOARD 	PORTD, PIN3
#define ENABLE_EXTERNAL_RSON_INTERFACE_EXPANSION_BOARD 	PORTB, PIN12, false

//CAN
#define CAN1_TX	PORTC, 		PIN10, OVERRID
#define CAN1_RX PORTC, 		PIN9, OVERRID
#define CAN1_ENABLE_TX_RX	PORTB, PIN11

#define CAN2_TX	PORTC, 		PIN12, OVERRID
#define CAN2_RX	PORTC, 		PIN11, OVERRID

//Device
const uint8_t VERSION_SPECIAL_SOFTWARE_THIS_MODULE = 2;

//Some default slave addresses
const uint8_t addressInputModule1 = 1;
const uint8_t addressInputModule2 = 2;
const uint8_t addressInputModule3 = 3;
const uint8_t addressOutputModule = 4;

#endif /* INC_DEVICE_H_ */
