#ifndef MTR_UART_DEFINES_H_
#define MTR_UART_DEFINES_H_

//Default values for 1986VE92 64MHz clock

#ifndef CONFIG_UART_HLCK
#define	CONFIG_UART_HLCK UART_HCLKdiv8
#endif

#ifndef CONFIG_UART_BUFFER_BYTE_SIZE
#define	CONFIG_UART_BUFFER_BYTE_SIZE 256
#endif

#ifndef CONFIG_UART_NVIC_PRIORITY
#define	CONFIG_UART_NVIC_PRIORITY 7
#endif

#ifndef CONFIG_UART_TIMER
#define	CONFIG_UART_TIMER TIMER3
#endif

#ifndef CONFIG_UART_TIMER_IRQ
#define	CONFIG_UART_TIMER_IRQ Timer3_IRQHandler
#endif

#ifndef CONFIG_UART_TIMER_DIV
#define	CONFIG_UART_TIMER_DIV 8
#endif

#ifndef CONFIG_UART_PROCESSING_RECIEVED_MESSAGE_IN_BYTES
#define	CONFIG_UART_PROCESSING_RECIEVED_MESSAGE_IN_BYTES 4
#endif

#ifndef CONFIG_UART_CALLBACKFUNC
#define	CONFIG_UART_CALLBACKFUNC MTR_Uart_callCallbacks
#endif


#endif /* MTR_UART_DEFINES_H_ */
